Only install required dependencies
JSanchezIO/parcel-plugin-inject-manifest-service-worker pull request #1
Opened 2021-02-09 04:31 UTC by nVitius

Thanks for writing this plugin; the other parcel plugins for workbox don't really support injectManifest very well.

Most of the dependencies in your package.json don't need to be installed by the end-user. This commit just moves them over to devDependencies.

2021-02-21 04:00 UTC, JSanchezIO commented
Thanks for doing this, I normally mark dependencies I need in CI as non `devDependencies` so I can run `npm ci` in pipelines. However, I forgot how that impacts a person using the package. I think we'll have to update the CI scripts to run `npm install` instead of `npm ci` and this should work.

2021-02-21 04:03 UTC, JSanchezIO requested changes
Let's update `.github/workflows/ci.yml` and `.github/workflows/cd.yml` to run `npm install` instead of `npm ci` under their respective **Install Dependencies** step and then we'll merge this.

2021-02-23 07:58 UTC, nVitius commented
I can make the changes, but a quick search shows that `npm ci` should also install `devDependencies` as long as you don't use `--production` or `NODE_ENV=production`.

Are you sure it won't work as-is? It looks like the CI job on the pull request passed successfully.

I haven't used `npm ci` before, so I can't say for sure. Let me know if you want me to make the changes anyway.

2021-02-24 23:35 UTC, JSanchezIO approved these changes

2021-02-24 23:36 UTC, merged